# Generated by Django 5.0.2 on 2024-03-05 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInvoice', models.IntegerField(default=0, unique=True, verbose_name='# Factura')),
                ('invoice_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha factura')),
                ('quantityItems', models.IntegerField(verbose_name='Cantidad de items')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Unidades')),
                ('subTotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalle Facturas',
                'db_table': 'detalle_factura',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
