# Generated by Django 5.0.2 on 2024-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_invoice_numberinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numberInvoice',
            field=models.IntegerField(default=0, unique=True, verbose_name='# Factura'),
        ),
    ]
