# Generated by Django 5.0.2 on 2024-03-07 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_alter_invoicedetail_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='numberInvoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha factura'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantityItems',
            field=models.IntegerField(default=0, verbose_name='Cantidad de items'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='subTotal',
            field=models.PositiveIntegerField(verbose_name='Subtotal'),
        ),
    ]
