# Generated by Django 5.0.2 on 2024-03-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_alter_invoicedetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='subTotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Subtotal'),
        ),
    ]
