# Generated by Django 5.0.2 on 2024-03-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0006_alter_supplier_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_order',
            name='suppliers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordencompra.suppliers', verbose_name='Proveedor'),
        ),
    ]
